# Generated by Django 5.2.15 on 2026-06-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_options_task_dependencies_task_eisenhower_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='project',
            name='color',
            field=models.CharField(blank=True, default='#0077B6', max_length=7),
        ),
    ]
