# Generated by Django 6.0.6 on 2026-06-23 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('key', models.CharField(max_length=128, unique=True)),
                ('created_at', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'api_key',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('completed', models.BooleanField(default=False)),
                ('stage', models.CharField(choices=[('notStarted', 'Not started'), ('inProgress', 'In progress'), ('waitingReview', 'Waiting for review'), ('complete', 'Complete')], default='notStarted', max_length=16)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=8)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('position', models.PositiveIntegerField(default=0)),
                ('completed_on', models.CharField(blank=True, default='', max_length=10)),
            ],
            options={
                'db_table': 'daily_task',
                'ordering': ['position'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeneralTask',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('completed', models.BooleanField(default=False)),
                ('stage', models.CharField(choices=[('notStarted', 'Not started'), ('inProgress', 'In progress'), ('waitingReview', 'Waiting for review'), ('complete', 'Complete')], default='notStarted', max_length=16)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=8)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'general_task',
                'ordering': ['position'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InboxMessage',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('sender', models.CharField(db_column='from', max_length=500)),
                ('message', models.TextField()),
                ('received_at', models.CharField(max_length=40)),
                ('read', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'inbox_message',
                'ordering': ['received_at'],
            },
        ),
        migrations.CreateModel(
            name='InboxTask',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=8)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('received_at', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'inbox_task',
                'ordering': ['received_at'],
            },
        ),
        migrations.CreateModel(
            name='Passkey',
            fields=[
                ('id', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('public_key', models.TextField()),
                ('counter', models.BigIntegerField(default=0)),
                ('transports', models.TextField(blank=True, default='[]')),
                ('name', models.CharField(default='Passkey', max_length=200)),
                ('created_at', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'passkey',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PendingChallenge',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'pending_challenge',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('priority', models.PositiveSmallIntegerField(default=5)),
                ('color', models.CharField(max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'project',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('timezone', models.CharField(default='America/Edmonton', max_length=64)),
                ('theme', models.CharField(default='dark', max_length=16)),
                ('general_color', models.CharField(max_length=32)),
                ('daily_color', models.CharField(max_length=32)),
                ('last_daily_reset_date', models.CharField(blank=True, default='', max_length=10)),
            ],
            options={
                'db_table': 'settings',
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('notes', models.TextField(blank=True, default='')),
                ('position', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='tracker.project')),
            ],
            options={
                'db_table': 'milestone',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('completed', models.BooleanField(default=False)),
                ('stage', models.CharField(choices=[('notStarted', 'Not started'), ('inProgress', 'In progress'), ('waitingReview', 'Waiting for review'), ('complete', 'Complete')], default='notStarted', max_length=16)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=8)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('position', models.PositiveIntegerField(default=0)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tracker.milestone')),
            ],
            options={
                'db_table': 'project_task',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_links', to='tracker.projecttask')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependency_links', to='tracker.projecttask')),
            ],
            options={
                'db_table': 'task_dependency',
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='projecttask',
            name='dependencies',
            field=models.ManyToManyField(related_name='dependents', through='tracker.TaskDependency', to='tracker.projecttask'),
        ),
        migrations.AddConstraint(
            model_name='taskdependency',
            constraint=models.UniqueConstraint(fields=('task', 'depends_on'), name='uniq_task_dependency'),
        ),
        migrations.AddConstraint(
            model_name='taskdependency',
            constraint=models.CheckConstraint(condition=models.Q(('task', models.F('depends_on')), _negated=True), name='no_self_dependency'),
        ),
    ]
